import Head from 'next/head'
// import Navbar from '@/components/home/Navbar'
import About from '@/components/home/About'
import Vision from '@/components/home/Vision'
import ImageSlider from '@/components/ImageSlider'
import Mission from '@/components/home/Mission'
import Footer from '@/components/common/Footer'
import { motion } from 'framer-motion'
import Image from 'next/image'
import ScrollToTopButton from '@/components/common/ScrollToTopButton '
import Navbar2 from '@/components/home/Navbar2'
import Link from 'next/link'

export default function Home() {
  const images = [
    '/coding.jpg',
    '/slider2.jpg',
    '/slider3.jpg',
    "/school front.jpg"
  ];
 
  return (
    <>
      <Head>
        <title>St Moses High School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
      <Navbar2/>

    <ImageSlider images={images}/>

 <div className='mission-container' style={{margin:"20px 0px 25px", padding:"0px 12px", alignItems:"flex-start"}} >
  <h2 className='mission-title' style={{margin:"5px 0px !important",}}>SMK Memorial Athletics Meet 2024: </h2>
<Link style={{color:"#3366CC", fontSize:"20px !important"}} href={"https://forms.gle/pd553NM1orPd3d3r5"} target="_blank">click here</Link>
</div>



<div className="coding">
<Image src={"/coding2.jpg"} width={"450"} height={"600"} className='coding-img' alt='Coding Enrollment'/>
</div>
      {/* <video src="/video1.mp4" autoPlay muted loop className='video'></video> */}

  <About/>
  <div className="location">
    <h2 className="subHeading">Location</h2>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3805.036269284354!2d78.4631603!3d17.505782!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb900fb5b9a82f%3A0x35d09c7a1a275241!2sSt.%20Moses%20High%20School!5e0!3m2!1sen!2sin!4v1687030094788!5m2!1sen!2sin" width="600" className='location-map' height="450" style={{border:"0"}} loading="lazy"></iframe>

<motion.div   
        initial={{ opacity: 0,translateX:150 }}
        transition={{duration:1.2 }} 
        whileInView={{opacity:1,translateX:0}}
        // animate={{ opacity: 1,scale:1}}
        >
<p className='locationPara'>It is located in Quthbullahpur, a serene locality accessible from the twin cities of Hyderabad and Secunderabad. The school has a spacious building and 4 acres of playground in a pollution free environment, away from the hustle bustle of the city. The school is very near to Suchitra X Roads on Medchal Highway. It is easily accessible from
Secunderabad, Alwal, Kompally, Bowenpally, Balanagar and several other areas.
</p>
</motion.div>
</div>

<Vision/>
  <Mission/>
  <ScrollToTopButton/>
  <Footer/>
    </>
  )
}
